<?php
/**
 * @file
 * wetkit_migrate.module
 */

include_once 'wetkit_migrate.features.inc';

/**
 * Implements hook_migrate_api().
 */
function wetkit_migrate_migrate_api() {
  $api = array(
    'api' => 2,

    // Migrations can be organized into groups. The key used here will be the
    // machine name of the group, which can be used in Drush:
    //  drush migrate-import --group=WetKitMigrate
    //
    // The title is a required argument which is displayed for the group in the
    // UI. You may also have additional arguments for any other data which is
    // common to all migrations in the group.
    'groups' => array(
      'WetKitGroupMigrate' => array(
        'title' => t('WetKitGroupMigrate Imports'),
      ),
    ),

    // Here we register the individual migrations. The keys below
    // are the machine names of the migrations, and the class_name
    // argument is required. The group_name is optional (defaulting to 'default')
    // but specifying it is a best practice.
    'migrations' => array(
      'WetKitMigrateDefaultContent' => array(
        'class_name' => 'WetKitMigrateDefaultContent',
        'group_name' => 'WetKitGroupMigrate',
      ),
      'WetKitMigrateDocumentation' => array(
        'class_name' => 'WetKitMigrateDocumentation',
        'group_name' => 'WetKitGroupMigrate',
      ),
      'WetKitMigrateDocumentationMenu' => array(
        'class_name' => 'WetKitMigrateDocumentationMenu',
        'group_name' => 'WetKitGroupMigrate',
      ),
      'WetKitMigrateDocumentationMenuLinks' => array(
        'class_name' => 'WetKitMigrateDocumentationMenuLinks',
        'group_name' => 'WetKitGroupMigrate',
      ),
      'WetKitMigrateMegaMenu' => array(
        'class_name' => 'WetKitMigrateMegaMenu',
        'group_name' => 'WetKitGroupMigrate',
      ),
      'WetKitMigrateMegaMenuLinks' => array(
        'class_name' => 'WetKitMigrateMegaMenuLinks',
        'group_name' => 'WetKitGroupMigrate',
      ),
    ),
  );
  return $api;
}

/**
 * Implements hook_migrate_menu().
 */
function wetkit_migrate_menu() {
  $items = array();

  $items['admin/panopoly/wetkit_settings/wetkit_migration'] = array(
    'title' => 'WetKit Migration',
    'description' => 'Configure database settings for the WetKit content migration.',
    'page callback' => 'drupal_get_form',
    'file' => 'wetkit_migrate.pages.inc',
    'page arguments' => array('wetkit_migrate_form'),
    'access callback' => TRUE,
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}
